Repository corona-warn-app/cwa-app-ccl, pull requests merged in 2022-09, with the labels that each got.

#102 Feature: Determine mask state (EXPOSUREAPP-13911)
  THIRD-PARTY-NOTICES
  lib/ccl/ccl-constants.js
  lib/ccl/ccl-jfn.js
  lib/ccl/ccl-main.js
  lib/ccl/functions/__analyzeDccWallet.js
  lib/ccl/functions/getDccAdmissionCheckScenarios.js
  lib/ccl/functions/getDccWalletInfo.js
  resources/i18n/de/strings.xml
  resources/json-schema/ccl-configuration.json
  resources/json-schema/ccl-get-dcc-admission-check-scenarios.json
  resources/json-schema/ccl-get-dcc-wallet-info.json
  scripts/export-ccl-test-cases.js
  test/fixtures/ccl/ccl-admission-check-scenarios.yaml
  test/fixtures/ccl/dcc-series-wallet-info-mask-state.yaml
  test/fixtures/ccl/dcc-series-wallet-info-scenario-identifier.yaml
  test/unit/ccl/functions/__analyzeDccWallet.spec.js
  test/unit/ccl/functions/getDccAdmissionCheckScenarios.spec.js
  test/unit/ccl/functions/getDccWalletInfo.spec.js
  test/util/fixtures.js
Labels: enhancement

#103 Feature: Remove admission state (EXPOSUREAPP-13914, EXPOSUREAPP-13916)
  lib/ccl/ccl-constants.js
  lib/ccl/functions/__analyzeDccWallet.js
  resources/i18n/de/strings.xml
  test/fixtures/ccl/dcc-series-bug-reports.yaml
  test/fixtures/ccl/dcc-series-janssen.yaml
  test/fixtures/ccl/dcc-series-recovery.yaml
  test/fixtures/ccl/dcc-series-sample.yaml
  test/fixtures/ccl/dcc-series-standard-vaccination.yaml
  test/fixtures/ccl/dcc-series-tests-only.yaml
  test/fixtures/ccl/dcc-series-valid-until.yaml
  test/fixtures/ccl/dcc-series-wallet-info-admission-state.yaml
  test/fixtures/ccl/dcc-series-wallet-info-tests-only.yaml
Labels: enhancement

#106 Feature: Display selected federal state in texts for mask state (EXPOSUREAPP-13911)
  lib/ccl/functions/getDccWalletInfo.js
  resources/i18n/de/strings.xml
  test/fixtures/ccl/dcc-series-wallet-info-mask-state.yaml
Labels: enhancement

#107 Feature: Determine vaccination state based on latest IfSG (EXPOSUREAPP-13915)
  lib/ccl/functions/__analyzeDccWallet.js
  resources/i18n/de/strings.xml
  test/fixtures/ccl/dcc-series-allowed-vaccines.yaml
  test/fixtures/ccl/dcc-series-wallet-info-vaccination-state.yaml
Labels: enhancement

#105 Chore: consolidate CCL release 3.3.x
  THIRD-PARTY-NOTICES
  lib/ccl/ccl-constants.js
  lib/ccl/ccl-jfn.js
  lib/ccl/ccl-main.js
  lib/ccl/functions/__analyzeDccWallet.js
  lib/ccl/functions/getDccAdmissionCheckScenarios.js
  lib/ccl/functions/getDccWalletInfo.js
  resources/i18n/de/strings.xml
  resources/json-schema/ccl-configuration.json
  resources/json-schema/ccl-get-dcc-admission-check-scenarios.json
  resources/json-schema/ccl-get-dcc-wallet-info.json
  scripts/export-ccl-test-cases.js
  test/dist/ccl-test-cases.spec.js
  test/fixtures/ccl/ccl-admission-check-scenarios.yaml
  test/fixtures/ccl/dcc-series-allowed-vaccines.yaml
  test/fixtures/ccl/dcc-series-bug-reports.yaml
  test/fixtures/ccl/dcc-series-janssen.yaml
  test/fixtures/ccl/dcc-series-recovery.yaml
  test/fixtures/ccl/dcc-series-sample.yaml
  test/fixtures/ccl/dcc-series-standard-vaccination.yaml
  test/fixtures/ccl/dcc-series-tests-only.yaml
  test/fixtures/ccl/dcc-series-valid-until.yaml
  test/fixtures/ccl/dcc-series-wallet-info-admission-state.yaml
  test/fixtures/ccl/dcc-series-wallet-info-mask-state.yaml
  test/fixtures/ccl/dcc-series-wallet-info-scenario-identifier.yaml
  test/fixtures/ccl/dcc-series-wallet-info-tests-only.yaml
  test/fixtures/ccl/dcc-series-wallet-info-vaccination-state.yaml
  test/unit/ccl/functions/__analyzeDccWallet.spec.js
  test/unit/ccl/functions/getDccAdmissionCheckScenarios.spec.js
  test/unit/ccl/functions/getDccWalletInfo.spec.js
  test/util/fixtures.js
Labels: test-all

#112 Translation Delivery
  resources/i18n/bg/strings.xml
  resources/i18n/en/strings.xml
  resources/i18n/pl/strings.xml
  resources/i18n/ro/strings.xml
  resources/i18n/tr/strings.xml
  resources/i18n/uk/strings.xml
Labels: translation

#114 Feature: Hide mask state by default (EXPOSUREAPP-13915)
  lib/ccl/functions/__analyzeDccWallet.js
  lib/ccl/functions/getDccAdmissionCheckScenarios.js
  lib/ccl/functions/getDccWalletInfo.js
  resources/i18n/de/strings.xml
  test/fixtures/ccl/ccl-admission-check-scenarios.yaml
  test/fixtures/ccl/dcc-series-wallet-info-mask-state.yaml
Labels: enhancement

#115 Translation Delivery
  resources/i18n/bg/strings.xml
  resources/i18n/en/strings.xml
  resources/i18n/pl/strings.xml
  resources/i18n/ro/strings.xml
  resources/i18n/tr/strings.xml
  resources/i18n/uk/strings.xml
Labels: translation
