Repository corona-warn-app/cwa-app-ccl, pull requests merged in 2022-03, with the labels that each got.

#43 Feat: consider expired RCs to accompany VCs for reissuance
  lib/ccl/functions/__analyzeDccWallet.js
  lib/ccl/functions/__determineCertificateReissuance.js
  test/fixtures/ccl/dcc-series-reissuance.yaml
  test/util/dcc/dcc-series.js
Labels: enhancement

#42 Translation Delivery
  resources/i18n/bg/strings.xml
  resources/i18n/en/strings.xml
  resources/i18n/pl/strings.xml
  resources/i18n/ro/strings.xml
  resources/i18n/tr/strings.xml
Labels: translation

#47 feat(ccl): disable reissuance of certificates
  lib/ccl/functions/__analyzeDccWallet.js
  test/fixtures/ccl/dcc-series-reissuance.yaml
Labels: enhancement

#46 Feat: expose notification text for admission state changes (EXPOSUREAPP-12179)
  lib/ccl/functions/getDccWalletInfo.js
  resources/i18n/de/strings.xml
  resources/json-schema/ccl-get-dcc-wallet-info.json
  test/fixtures/ccl/dcc-series-wallet-info-admission-state.yaml
  test/fixtures/ccl/dcc-series-wallet-info-tests-only.yaml
  test/unit/ccl/functions/getDccWalletInfo.spec.js
Labels: enhancement

#54 Feature: Support old encoding for novavax (EXPOSUREAPP-12348)
  lib/ccl/functions/__analyzeDccWallet.js
  test/fixtures/ccl/dcc-series-allowed-vaccines.yaml
  test/util/dcc/dcc-series.js
Labels: enhancement

#55 Feature: Deprioritize booster RCs after 90 days (EXPOSUREAPP-12366)
  lib/ccl/functions/__analyzeDccWallet.js
  test/fixtures/ccl/dcc-series-recovery.yaml
Labels: enhancement

#58 Translation Delivery (Ukrainian)
  resources/i18n/uk/strings.xml
Labels: translation

#59 Feature: Revise texts for vaccination status (EXPOSUREAPP-11928)
  lib/ccl/ccl-jfn.js
  lib/ccl/functions/__analyzeDccWallet.js
  lib/ccl/functions/getDccWalletInfo.js
  lib/ccl/functions/getVaccinationStateLongTextV2.js
  resources/i18n/de/strings.xml
  test/fixtures/ccl/dcc-series-allowed-vaccines.yaml
  test/fixtures/ccl/dcc-series-bug-reports.yaml
  test/fixtures/ccl/dcc-series-janssen.yaml
  test/fixtures/ccl/dcc-series-recovery.yaml
  test/fixtures/ccl/dcc-series-standard-vaccination.yaml
  test/fixtures/ccl/dcc-series-wallet-info-tests-only.yaml
  test/fixtures/ccl/dcc-series-wallet-info-vaccination-state.yaml
  test/fixtures/ccl/ir-tx-0002.json
Labels: enhancement

#61 Fix: set FAQ anchor for DCC reissuance
  lib/ccl/functions/getDccWalletInfo.js
  test/fixtures/ccl/dcc-series-reissuance.yaml
  test/unit/ccl/functions/getDccWalletInfo.spec.js
Labels: bug

#56 Feature: Revoke DCCs via Invalidation Rules (EXPOSUREAPP-12407)
  lib/ccl/ccl-jfn.js
  lib/ccl/functions/__evaluateInvalidationRules.js
  lib/ccl/functions/getDccWalletInfo.js
  resources/json-schema/ccl-get-dcc-wallet-info.json
  test/fixtures/ccl/dcc-series-wallet-info-ir.yaml
  test/fixtures/ccl/ir-tx-0001.json
  test/unit/ccl/functions/getDccWalletInfo.spec.js
  test/util/fixtures.js
Labels: enhancement

#63 Fix: correctly escape line breaks in translated texts (EXPOSUREAPP-12510)
  lib/ccl/ccl-i18n.js
  test/fixtures/ccl/dcc-series-reissuance.yaml
Labels: bug

#64 Translation Delivery
  resources/i18n/bg/strings.xml
  resources/i18n/en/strings.xml
  resources/i18n/pl/strings.xml
  resources/i18n/ro/strings.xml
  resources/i18n/tr/strings.xml
  resources/i18n/uk/strings.xml
Labels: translation
