Repository corona-warn-app/cwa-app-ccl, pull requests merged in 2022-05, with the labels that each got.

#76 Feature: Support reissuing of expired certificates (EXPOSUREAPP-12970)
  lib/ccl/ccl-constants.js
  lib/ccl/ccl-jfn.js
  lib/ccl/functions/__analyzeDccWallet.js
  lib/ccl/functions/__determineCertificateReissuanceForExtend.js
  lib/ccl/functions/__determineCertificateReissuanceForRenew.js
  lib/ccl/functions/getDccWalletInfo.js
  resources/i18n/de/strings.xml
  resources/json-schema/ccl-commons.json
  resources/json-schema/ccl-get-dcc-wallet-info.json
  test/fixtures/ccl/dcc-series-reissuance-extend.yaml
  test/fixtures/ccl/dcc-series-reissuance-renew.yaml
  test/unit/ccl/functions/__analyzeDccWallet.spec.js
  test/unit/ccl/functions/getDccWalletInfo.spec.js
Labels: enhancement

#78 Fix: German genitive without 'e' (EXPOSUREAPP-13051)
  resources/i18n/de/strings.xml
Labels: bug

#77 Translation Delivery
  resources/i18n/bg/strings.xml
  resources/i18n/en/strings.xml
  resources/i18n/pl/strings.xml
  resources/i18n/ro/strings.xml
  resources/i18n/tr/strings.xml
  resources/i18n/uk/strings.xml
Labels: translation

#79 Fix: typo in German text
  resources/i18n/de/strings.xml
  test/fixtures/ccl/dcc-series-reissuance-renew.yaml
Labels: bug

#80 Feature: Same date handling for certificate extension (EXPOSUREAPP-12970)
  lib/ccl/functions/__determineCertificateReissuanceForExtend.js
  test/fixtures/ccl/dcc-series-reissuance-extend.yaml
Labels: enhancement

#81 Fix: vaccines of certificates must be on the allowlist for extension (EXPOSUREAPP-13153)
  lib/ccl/ccl-constants.js
  lib/ccl/functions/__analyzeDccWallet.js
  lib/ccl/functions/__determineCertificateReissuanceForExtend.js
  test/fixtures/ccl/dcc-series-reissuance-extend.yaml
  test/util/dcc/dcc-series.js
Labels: bug

#82 Fix: display FAQ anchor for vaccination state (EXPOSUREAPP-12942)
  lib/ccl/functions/getDccWalletInfo.js
  test/fixtures/ccl/dcc-series-wallet-info-vaccination-state.yaml
Labels: bug
