Repository corona-warn-app/cwa-app-ccl, pull requests merged in 2022-12, with the labels that each got.

#129 Feature: Support WHO-approved vaccines (EXPOSUREAPP-14352)
  lib/ccl/ccl-constants.js
  lib/ccl/functions/__analyzeDccWallet.js
  test/fixtures/ccl/dcc-series-wallet-info-vaccination-state.yaml
  test/util/dcc/dcc-series.js
Labels: enhancement

#127 Upgrade github actions with new node version
  .github/workflows/ci.yml
  .github/workflows/pr-validation.yml
  .github/workflows/release.yml
Labels: mirrored-to-jira

#125 Translation Delivery
  resources/i18n/bg/strings.xml
  resources/i18n/en/strings.xml
  resources/i18n/pl/strings.xml
  resources/i18n/ro/strings.xml
  resources/i18n/tr/strings.xml
  resources/i18n/uk/strings.xml
Labels: translation
